### ISSUE TITLE
order of stratified vpc plots

### ISSUE THREAD

**Issue by oskarrgh** [UUPharmacometrics/xpose#110]
First of all, thanks for a great package! When generating vpc data based on non-PsN generated simulations the order of elements in column "strat" and the columns containing the stratification variables (both in data frame "vpc_dat" and "aggr_obs") seems to be based on data class character. This although the stratification variable in problem 1 and 2 are data class factor, with appropriate levels and ordering. This can results in unexpected ordering of vpc plots when stratification variable is for example 2, 5 and 10, where 10 then will be ordered before 2 and 5. If my understanding is correct, is it possible to not do this intermediate transformation of the stratification variables during vpc data generation or is there any obvious solution/feature that I have missed?

**Comment by oskarrgh** [comment]
Thanks for the fast reply @guiastrennec, 
I will get back to you asap with regards to a reproducible example. Meanwhile I can confirm that the suggested features did solved my issue by enabling transformation of the variable into a factor and setting the appropriate levels. 
```
xpdb %>% 
vpc_data(stratify=c("DOSE") %>%
mutate(DOSE = factor(DOSE, levels=c("2", "5", "10"), ordered=TRUE),
         .source = "special", 
         .where = "vpc_dat") %>%
mutate(DOSE = factor(DOSE, levels=c("2", "5", "10"), ordered=TRUE),
         .source = "special", 
         .where = "aggr_obs") %>%
mutate(DOSE = factor(DOSE, levels=c("2", "5", "10"), ordered=TRUE),
         .source = "special", 
         .where = "obs") %>%
vpc(facets=c("DOSE"))
```
Would be good to have the feature documented as I failed to figure out how to do this prior to my first post. Still curious if it would be possible to retain the data class set in problem 1 and 2 when generating data for problem 3. I think that would convenient not to have to modify variables more than once. Keep up the good work!

**Comment by AnhDucPham** [comment]
Hi, 
I have over 200 plots and got the same issue with the ordering. I did padding the factor level of $strat with '00' in vpc_dat, aggr_obs, obs by formatC(). 
Hope it can help.

**Comment by JoannaPeng** [comment]
@bguiastr, how to re-order of stratified vpc plots with 2 stratifiers (e.g., DAY and DOSE)? DAY has two values (1, 15), and DOSE has three values (60, 80, 120). I used the code below; however, the 120 dose is still shown in front of the 60 and 80 dose. 

vpc_data=vpc_data(xpdb,psn_folder="@dir/@run_TAD_DAY_DOSE",psn_bins=TRUE,stratify=DAY~DOSE) 

vpc_special <- get_special(vpc_data)

vpc_data=vpc_data%>% 
  mutate(strat=factor(strat,levels=c('1, 60','1, 80','1, 120','15, 60','15, 80','15, 120'),ordered=TRUE), .source = 'special', .where = 'vpc_dat')%>%
  mutate(strat=factor(strat,levels=c('1, 60','1, 80','1, 120','15, 60','15, 80','15, 120'),ordered=TRUE), .source = 'special', .where = 'aggr_obs')%>%
  mutate(strat=factor(strat,levels=c('1, 60','1, 80','1, 120','15, 60','15, 80','15, 120'),ordered=TRUE), .source = 'special', .where = 'obs')

**Comment by bguiastr** [comment]
@JoannaPeng, the approach you used to relabel the factors should work you are probably close to the answer ! Two suggestions from my end:

1) You might find it easier to create a new variable in your dataset which would be taking values based on your `DAY` and `DOSE` variables. This allows you to stratify on 2 or more variable without difficulty and apply the code I provided in ![my earlier example](https://github.com/UUPharmacometrics/xpose/issues/110#issuecomment-414355186).

2) Beware that you need to edit the variable **strat** in `vpc_dat` (summary of simulations), and `aggr_obs` (summary of observations) as well as your **stratification variable** (which might not be called `strat` as I see in your example code) in `obs` (raw observations).

Hope it helps!

**Comment by JoannaPeng** [comment]
@bguiastr, thanks for your help. I figured out how to fix this problem. For my code above, I should mutate "DOSE", not "strat", as an ordered factor. It is because the plotting uses "DOSE" (and "DAY"), not "strat".

**Comment by bguiastr** [comment]
Glad it solved your problem !
