### ISSUE TITLE
Calculation of PI in VPC

### ISSUE THREAD

**Issue by Vincent-AC** [UUPharmacometrics/xpose#111]
Hello,
First of all thank you for all your work in making this new xpose package for ggplot enthusiasts !

I have an issue with how percentiles are calculated for VPCs prediction intervals. There seems to be a difference between this new package and PsN + xpose4

In PsN for a i-th percentile of the simulations, first pooling the simulated DVs from all the NONMEM simulation runs is done then the percentile is determined on this data.

Here, it seems that the i-th percentile of the simulation, first this percentile is determined separately on DV from each NONMEM simulation run, and then the median of all those calculated percentiles is calculated. That it as least how I interpret the code coming from the vpc package [link starting line 250](https://github.com/ronkeizer/vpc/blob/master/R/vpc.R) :
 
` if(verbose) message("Calculating statistics for simulated data...")
    tmp1 <- sim %>% dplyr::group_by(strat, sim, bin)
    aggr_sim <- data.frame(cbind(tmp1 %>% dplyr::summarise(quantile(dv, pi[1])),
                                 tmp1 %>% dplyr::summarise(quantile(dv, 0.5 )),
                                 tmp1 %>% dplyr::summarise(quantile(dv, pi[2])),
                                 tmp1 %>% dplyr::summarise(mean(idv))))
    aggr_sim <- aggr_sim[,-grep("(bin.|strat.|sim.)", colnames(aggr_sim))]
    colnames(aggr_sim)[grep("quantile", colnames(aggr_sim))] <- c("q5", "q50", "q95")
    colnames(aggr_sim)[length(aggr_sim[1,])] <- "mn_idv"
    tmp <- aggr_sim %>% dplyr::group_by(strat, bin)
    vpc_dat <- data.frame(cbind(tmp %>% dplyr::summarise(quantile(q5, ci[1])),
                                tmp %>% dplyr::summarise(quantile(q5, 0.5)),
                                tmp %>% dplyr::summarise(quantile(q5, ci[2])),
                                tmp %>% dplyr::summarise(quantile(q50, ci[1])),
                                tmp %>% dplyr::summarise(quantile(q50, 0.5)),
                                tmp %>% dplyr::summarise(quantile(q50, ci[2])),
                                tmp %>% dplyr::summarise(quantile(q95, ci[1])),
                                tmp %>% dplyr::summarise(quantile(q95, 0.5)),
                                tmp %>% dplyr::summarise(quantile(q95, ci[2])),
tmp %>% `dplyr::summarise(mean(mn_idv)))) `

I guess that the median of the calculated percentiles should be equivalent to the percentile over all the data when the quantity of data tends to infinity but it is different enough that it shows with the model I am working on currently. Was there any specific reason for this change ? Could one method be especially better than the other ?

Thanks a lot !

**Comment by smouksassi** [comment]
should'nt we open this on the vpc repo ?  you can click on a line number and ad it to the link e.g.
https://github.com/ronkeizer/vpc/blob/master/R/vpc.R#L250 
Note that to be able to do the confidence interval  VPC over the replicates we need to do that and I am not sure there is an option to do the old "scatter vpc" which is less informative. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5321813/

**Comment by guiastrennec** [comment]
Hello,

Thank you for reviewing the code so thoroughly. As mentioned by @smouksassi the issue you are describing is related to the code from the vpc package, for which xpose is only a wrapper. So I suggest that you post this issue [here](https://github.com/ronkeizer/vpc/issues) instead.

Best of luck!

**Comment by Vincent-AC** [comment]
Thanks for your answer, I'll take the discussion there.
