### ISSUE TITLE
prefix of "run"?

### ISSUE THREAD

**Issue by jzhou2009** [UUPharmacometrics/xpose#133]
I found out the xpose_data requires .lst files must start with "run", e.g. "run1.lst", and it does not take "1.lst" as the prefix of "run" was added to run number in the new xpose. Is there any way to fix this?

Thank you!
Regards,
Jie

**Comment by guiastrennec** [comment]
@jzhou2009 by default xpose works by combining the arguments `prefix = "run"`, runno and `ext =  ".lst"`. You can either change the prefix to match your naming convention OR you can ignore these 3 arguments and use the `file` argument instead.

You can read more about the way these arguments work in the [xpose documentation](https://uupharmacometrics.github.io/xpose/reference/xpose_data.html)
