### ISSUE TITLE
Feature Request: coef and vcov methods for xpose_data

### ISSUE THREAD

**Issue by billdenney** [UUPharmacometrics/xpose#141]
I've recently been wanting to simplify confidence interval generation for xpose_data objects.  As a first, naive attempt, I tried calling `confint()` on my xpdb.  That didn't work, so I dug a bit deeper, and the default confint method only requires a `coef` and `vcov` method.

I wrote the following a simple wrappers, but I know that I didn't do problem/subproblem/method selection correctly.  Also, when using the Bayesian methods, it would be useful to use the quantiles of the sampling phase rather than the asymptotic CI.

What would you think about cleaning these up and adding them to xpose?

```r
coef.xpose_data <- function(object, ..., .problem=NULL, .subprob=NULL, .method=NULL) {
  ret <- get_prm(xpdb=object, .problem=.problem, .subprob=.subprob, .method=.method, digits=Inf, show_all=TRUE, ...)
  setNames(ret$value, ret$name)
}

vcov.xpose_data <- function(object, ..., .problem=NULL, .subprob=NULL, .method=NULL) {
  cov_data <- object$files$data[[which(object$files$extension == "cov")]]
  ret <- as.matrix(cov_data[, setdiff(names(cov_data), "NAME")])
  rownames(ret) <- cov_data$NAME
  ret
}
```

**Comment by guiastrennec** [comment]
Do you think this should be added in the core xpose or an add-on? When times allow I will transition xpose into S3 so it would allow more flexibility for this type of initiative.

**Comment by billdenney** [comment]
To me, coef and vcov are methods that assist with model summaries, so I think that they are core.

**Comment by guiastrennec** [comment]
Why not the code is relatively simple and we could add these to the `summary()` output

**Comment by guiastrennec** [comment]
As stated in #158 I no longer believe that the R model objects functions should be part of the main `xpose` code, but I recommend a separate extension package instead.
