### ISSUE TITLE
Xpose is no longer available on CRAN

### ISSUE THREAD

**Issue by jeroenes** [UUPharmacometrics/xpose#142]
As the title says - it seems to have been removed because of unresolved issues. I just tried to install xpose freshly and it came back as unavailable.  Would be great if it would be made available again.

Thanks,
Jeroen

**Comment by guiastrennec** [comment]
Sorry about that I have been very busy for some time now. I just resubmitted to CRAN 0.4.4 will hopefully be released tomorrow!
