### ISSUE TITLE
Error reading data to xpose

### ISSUE THREAD

**Issue by Kagedal** [UUPharmacometrics/xpose#149]
When reading the data into xpose I get the following messages:
   Looking for nonmem output tables.
   Reading: sdtab1, patab1, cotab1, catab1 [$prob no.1]
   Looking for nonmem output files
   Reading: run1.cor, run1.cov, run1.ext, run1.phi
   Warning message:
   `data` = out must be a symbol or a string, not a formula 

When running list_vars(xpdb) I get
   No `data` slot could be found in this xpdb

Not sure what is wrong. It used to be working.

**Comment by guiastrennec** [comment]
@Kagedal I cannot reproduce your error! Here is my suggestion:
1. Check that the .cor, .cov, .ext and .phi are present with the .lst file?
2. Make sure R, xpose and tidyverse are up to date *(note: xpose 0.4.4 was just released last night).*
3. Try the following example code:
```r
library(xpose)

xpdb <- xpose_data(file = system.file('extdata', 'run001.lst', package = 'xpose')) 

list_vars(xpdb)
```

This should give you the list of variables for the xpose example and you should not be getting any error. If you do please send me your `sessionInfo()`

**Comment by Kagedal** [comment]
Thanks Benjamin,
After updating tidyverse it is working again!
Matts
