### ISSUE TITLE
Question about eta_distrib plot

### ISSUE THREAD

**Issue by UNCcrawler** [UUPharmacometrics/xpose#165]
Hi, I have a question about the eta_distrib plot and hope you could help me understand the plot better. 
As shown below (or attached), there are few grey bars in two of the bottom plots. I don't understand what are these grey bars. Could you please explain this to me? Thanks! 
[test.pdf](https://github.com/UUPharmacometrics/xpose/files/3663376/test.pdf)

**Comment by michielve** [comment]
If I am correct, this is a so called rug plot. The default type for the eta distribution is type="hr".
It is a single tick for each individual observation.

http://rfunction.com/archives/390

An xpose example is given here and how to change the type:
https://uupharmacometrics.github.io/xpose/reference/distrib_plot.html

**Comment by guiastrennec** [comment]
@UNCcrawler as nicely pointed out by @michielve the ticks at the bottom of distributions plots such as histograms or density are indeed called a rug and are meant to indicate where individual observations are falling. It is best to use these rugs when the data is relatively sparse as it may helps to avoid over interpretation of trends (e.g. in your case the ETA(2) with the SC study) especially with density kernels by reminding you of the sparseness of the data. 

If you would like to read more about it xpose makes use of [geom_rug()](https://ggplot2.tidyverse.org/reference/geom_rug.html) from ggplot2.

**Comment by UNCcrawler** [comment]
Thank you for help. Now I see the light grey bars behind the dark grey bars are showing the density of observations. Thank you for taking the time to help me! @michielve @guiastrennec

**Comment by guiastrennec** [comment]
@UNCcrawler, from the look of your plot I do not think that you have density kernels in there (i.e. type = 'd') and I do not know why you have 2 types of bars... If you send me a reproducible example I can look into it, but by default the histogram (with the rug) should look like this in xpose:

```prm_distrib(xpdb_ex_pk, type = 'hr')```
![test](https://user-images.githubusercontent.com/7304883/66074405-6de3b380-e559-11e9-8060-3680a9d33817.png)

If instead you want to look at the density plot with the rug as mentioned previously it should look like this:
``` prm_distrib(xpdb_ex_pk, type = 'dr')```
![test2](https://user-images.githubusercontent.com/7304883/66074414-71773a80-e559-11e9-84be-ee8227fb2a70.png)

**Comment by UNCcrawler** [comment]
Thank you! I just figured it out. It was a syntax error. I apologize for
wasting your time.
