### ISSUE TITLE
Error column string must be length 1 since tidyr update 

### ISSUE THREAD

**Issue by michielve** [UUPharmacometrics/xpose#166]
After updating the tidyr package to the latest version (V1.0, since 11-sep-2019) I am unable to create an xpose_data object. I get the following error:
`Column string must be length 1 (the group size), not 2`

After some troubleshooting I found that the error originates from the creation of the table_list object in the list_nm_tables function.

`  table_list <- table_list %>% dplyr::group_by_(.dots = c("problem", 
        "level")) %>% tidyr::nest() %>% dplyr::mutate(string = purrr::map_chr(.$data, 
        ~stringr::str_c(.$code, collapse = " "))) %>% dplyr::mutate(file = stringr::str_match(.$string, 
        "\\s+FILE\\s*=\\s*([^\\s]+)")[, 2]) %>% dplyr::filter(!is.na(.$file))`

Installing the previous version of tidyr solved the issue for me. 

Thanks,
Michiel

**Comment by guiastrennec** [comment]
Thank you very much for the bug report, I am aware of this issue and will release 0.4.5 by the end of the week to CRAN to fix this.

**Comment by guiastrennec** [comment]
Fixed in 0.4.5
