### ISSUE TITLE
libPath_only not defined

### ISSUE THREAD

**Issue by Mutaz94** [UUPharmacometrics/xpose#182]
Hi! I always get the error that libPath_only=TRUE is not defined. Is there any way to fix it?

**Comment by guiastrennec** [comment]
Hi @Mutaz94, please start by updating xpose to the latest verion. If the bug persists please add a reproducible. It is otherwise not possible for me to help you.

**Comment by Mutaz94** [comment]
I think this is xpose4 issue. Sorry for the confusion. I did update xpos4, and xpose. This problem persists when using the templates generated by `-rplots=1` and the Error I get is: 
`
Error in R_info(directory = working.directory, only_libPaths = T) : 
  unused argument (only_libPaths = T)
` 

When I do delete only_libPaths=T . it works, but I don't think this is the best practice to do?

**Comment by guiastrennec** [comment]
I am sorry I am not familiar with this code, I recommend that you open an issue on [xpose4](https://github.com/UUPharmacometrics/xpose4/issues) or from the option `-rplots=1` I am guessing you are using PsN so you may also open an issue in the [PsNR](https://github.com/UUPharmacometrics/PsNR/issues) repo.
