### ISSUE TITLE
change the span value for plot

### ISSUE THREAD

**Issue by HuixiZou** [UUPharmacometrics/xpose#186]
Hi,

I am wondering if it possible to change the span value in xpose? 
I noticed that the code `smooth_method="lm"` could be used to customize the plots and make the line smoother. But I want to know if it possible to directly change the span value to customize the plots? 

Thanks a lot!

**Comment by guiastrennec** [comment]
Hello,

Yes all options available in the different geoms are available automatically in xpose. For the geom_smooth layer simply append "smooth_" in front of the argument name in your case simply use "smooth_span = 0.75" and it should work. In general you can see the names associated to the different geoms in the help of the xpose plot functions.

Best,

Benjamin

**Comment by HuixiZou** [comment]
Many Thanks!
