### ISSUE TITLE
Enhancement: line of identity

### ISSUE THREAD

**Issue by kestrel99** [UUPharmacometrics/xpose#19]
The line of identity is currently grey by default, which makes it hard to see against the data, which are also grey by default. Suggest the default be changed to another colour, like red or blue.

**Comment by guiastrennec** [comment]
I can darken the unity line a bit in the default theme. However in `theme_xp_default()` points are black and the unity line is light blue. Feel free to add more xpose themes !

**Comment by guiastrennec** [comment]
After some more thoughts I have changed the unity line to a thiner but black line that now lays on top of points an line to remain visible (#23). It looks like this:

![identity_line](https://user-images.githubusercontent.com/7304883/29455363-3503bec6-8411-11e7-9c98-d6c5a69452fd.png)

**Comment by guiastrennec** [comment]
After many tests I came to the conclusion that your suggestion was better and I have updated the theme with a red unity line #24
