### ISSUE TITLE
xpose 0.4.12, vpc

### ISSUE THREAD

**Issue by NilsJohan** [UUPharmacometrics/xpose#190]
I have used PsN 5.0.0. to run a VPC  and use the output to generate a plot via xpose 0.4.12 based on the following code:

setwd("C:/.../FP_sham_model_VPC_SIM3")
  vpc_data(xpdb,psn_folder = "vpc_dir6")%>% 
  vpc() 

The automatically generated R-plot via PsN extend simulations to include the last data point (1), whereas the plot generated via xpose 0.4.12 using the PsN output ends between the last and second last time point (2). I would appreciate any piece of advice on how to customize vpc_data() or vpc() in order to extend the simulation percentiles when using  xpose 0.4.12?

Thank you in advance and kind regards,

Johan

1. [PsN_vpc_plots.pdf](https://github.com/UUPharmacometrics/xpose/files/5886333/PsN_vpc_plots.pdf)

2. ![image](https://user-images.githubusercontent.com/8733245/106122229-bf558000-6158-11eb-9e55-c35a7f2889a1.png)

**Comment by smouksassi** [comment]
from above you want to edit how the binning is done by default it connects to the middle of the last bin between 40 and 50
( you can also do lot of other things including different binning algorithm by strata using https://github.com/certara/tidyvpc
