### ISSUE TITLE
add horizontal line at 0 for CWRES v.s IPRED 

### ISSUE THREAD

**Issue by tonggne** [UUPharmacometrics/xpose#192]
Hello xpose developer,
I am using xplot_scatter to create CWRES v.s IPRED plot (see below), but do not know how to add the horizontal line at 0. The guide = TRUE is only for the line of unity.

CWRES_vs_IPRED<-xpdb %>%
  filter(BLQ == 0) %>%
  xplot_scatter(aes(x = IPRED, y = CWRES), title = "CWRES v.s IPRED", subtitle = runno, caption = NULL)

Thanks a lot
Tong

**Comment by guiastrennec** [comment]
Hello,

All xpose plots are ggplot2 objects meaning that you can customize them as you wish with ggplot2 layers. For example
```
xpdb %>%
filter(BLQ == 0) %>%
xplot_scatter(aes(x = IPRED, y = CWRES), title = "CWRES v.s IPRED", subtitle = runno, caption = NULL) + 
geom_hline(yintercept = c(-2, 2), linetype = "dashed")
```
