### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [UUPharmacometrics/xpose#193]
Hi

We are preparing the next release of ggplot2 and our tests show issues with xpose. Specifically we have changed the signature of ggsave has changed (there are additional units options) and your forwarding of arguments in `xpose_save()` now fails.

We plan to submit the next version of ggplot2 to CRAN on May 31st

best
Thomas

**Comment by andrewhooker** [comment]
Hi Thomas,

Thanks.  We will try to get a fix in place before that.  Thanks for the heads-up!

Best regards, 
Andy
