### ISSUE TITLE
xpose didn't recognize all ETAs when interoccasion variability was used

### ISSUE THREAD

**Issue by UNCcrawler** [UUPharmacometrics/xpose#195]
Hi, I am using get_data() to read the nonmem output. I have five ETAs but get_data() only read four. I confirmed that ETA5 was in the patab output and not all zero. Similarly, ETA5 was dropped in eta_distrib(). I noticed that this only occurs when I am using interoccasion variability.
Could you please suggest what could be possibly wrong? Of course, I can directly read the patab file as a workaround, but I still prefer to use this package. 

Below is the nonmem code in case it is relevant. 
$OMEGA
 0.217 	;[1-IIV CL]
 0.172 	;[2-IIV V]
$OMEGA BLOCK(1) 0.1 	;[3-IIV KA]
$OMEGA BLOCK(1) SAME 	
$OMEGA BLOCK(1) SAME

**Comment by guiastrennec** [comment]
Hello, the `get_data()` function should not drop any column it is only a convenience function which returns the aggregated data from the xpdb. Would it be possible for you to send me a reproducible example so that I could look into your issue?

**Comment by UNCcrawler** [comment]
Hello, sorry for the late response. I am not able to send over the data due to confidentiality reason. I also moved away from that particular model and found out my other models with interoccasion variability work fine. Thank you for your time.
