### ISSUE TITLE
files locked due to readr's lazy loading

### ISSUE THREAD

**Issue by AndreasCalvagone** [UUPharmacometrics/xpose#198]
Hi,
since reader version 2.0.0 they changed the default argument of the readr functions (read_csv, read_lines, read_delim) to lazy=TRUE.
This is problematic since this 'lazy loading' means, at least on Windows computers, that the files are locked-up until you restart the R session. I find this a very annoying behavior while the benefit of lazy=TRUE will typical not materialize in our work.
I suggest to add lazy=FALSE to all places that make use of the above mentioned read functions.

**Comment by guiastrennec** [comment]
Hi Andreas, 
I have never faced this issue. I agree to add `lazy = FALSE` in future releases as it does not make sense to have lazy loading in the xpdb.

In the meantime you could try to use `lazy = FALSE` in `xpose_data()` or `read_nm_tables()` since you can send options to readr via the `...` argument.

**Comment by AndreasCalvagone** [comment]
Hi Benjamin,
thank you for your response. Unfortunately, the `...` solution doesn't work. I believe it is because in `read_nm_tables()` the table files are first accessed with a call to `read_lines()` to read in the first 3 lines before, later on, the whole dataset is then read with `read_args().`
The `...` is not passed on to the `read_lines()` function.
I have seen that the developers of readr acknowledged the issue and will add the possibility of `lazy=FALSE` to be set as a global option. That may be a solution until a new release of xpose.
Best regards, Andreas.

**Comment by guiastrennec** [comment]
Hi, 

Sorry for the time it took, but I am preparing a new release of `xpose` for compatibility issues with updates in the `tidyverse` and I was wondering if this is still an open issue?

It seems that the default behavior of `readr` has been pushed back to `lazy = FALSE`, and there is now the possibility to give global control over this argument with `options(readr.read_lazy = TRUE)`.

**Comment by AndreasCalvagone** [comment]
Hi,
indeed since the default is `lazy=FALSE`, there is no problem anymore. Though you may want to implement a check of the global option and issue a warning message if you find `readr.read_lazy = TRUE`.
