### ISSUE TITLE
Vpc stratification based on multiple variable 

### ISSUE THREAD

**Issue by faisalhhu** [UUPharmacometrics/xpose#204]
Hi I have a question
I have dataset with CMT column for compartment. I want to startify based on pediatric age groups. So in the data I coded the age groups as 1,2,3 and gave column name GRP.
Now when I run VPC Command using -stratify_on=c(CMT,GRP) or stratify_on=‘CMT’~’GRP’
It gives error with termination.

can you kindly help on what I am missing.

thanks
Faisal

**Comment by guiastrennec** [comment]
Hello,

The R package `xpose` is perfectly capable of handling up to 2 variables for stratification (see example below). The argument for stratification is `stratify` and not `stratify_on`.  Based on the look of your code I guess that you may have been referring to PsN code. Please know that as far as I know PsN does not handle more than one variable for the VPC stratification. I you want to use PsN for generating your VPCs you can generate a new variable in your NONMEM dataset that is defined by unique combination of the CMT and GRP columns.

``` r
library(xpose)
#> Loading required package: ggplot2
#> 
#> Attaching package: 'xpose'
#> The following object is masked from 'package:stats':
#> 
#>     filter
xpdb_ex_pk %>% 
  
  ## Create a second categorical covariate because only 1 was available in the example
  mutate(AGEGR = ifelse(AGE >= 66, 1, 0)) %>% 
  
  ## Generate the VPC data
  vpc_data(stratify = c('SEX', "AGEGR"), opt = vpc_opt(n_bins = 7, lloq = 0.1)) %>% 
  
  ## Plot the VPC
  vpc()
#> 
#> VPC continuous --------------------
#> 1. Gathering data & settings
#> Using xpdb simulation problem 2 and observation problem 1.
#> Setting stratifying variable to SEX, AGEGR
#> Setting lloq to 0.1.
#> 
#> 2. Computing VPC data
#> Configuring and initializing...
#> Stratifying oberved data...
#> Parsing observed data...
#> Filtering rows where EVID not 0
#> Parsing simulated data...
#> Filtering rows where EVID not 0
#> Binning: 0 0.66667 1.25 1.8 3 5 7 9
#> Calculating statistics for simulated data...
#> Calculating statistics for observed data...
#> 
#> VPC done
#> Warning: Combining variables of class <character> and <numeric> was deprecated in
#> ggplot2 3.4.0.
#> ℹ Please ensure your variables are compatible before plotting (location:
#>   `combine_vars()`)
#> Warning: Combining variables of class <numeric> and <character> was deprecated in
#> ggplot2 3.4.0.
#> ℹ Please ensure your variables are compatible before plotting (location:
#>   `combine_vars()`)
#> Warning: Removed 7 rows containing missing values (`geom_line()`).
#> Warning: Removed 25 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/4gPAZD1.png)

<sup>Created on 2022-10-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
