### ISSUE TITLE
Coloring points by column value

### ISSUE THREAD

**Issue by sn248** [UUPharmacometrics/xpose#209]
I am trying to color points in the `dv_vs_pred` plot by values in one of the column (e.g., treatment) but I am not to specify it in correct syntax. Can you help? I am trying

`dv_vs_pred(xpdb = xpdb %>% filter(CMT == 2), point_color = as.factor(TRT))`

This is the message I get

```
Using data from $prob no.1
Filtering data by EVID == 0
Error in parse_arg(x = list(...), name = name) : object 'TRT' not found
```

I can confirm that `TRT` is a column in the `xpdb` data.

Thanks!

**Comment by smouksassi** [comment]
see example below from built-in xpose database you need to use the mappings as in regular ggplot2

``` r
library(xpose)
#> Loading required package: ggplot2
#> 
#> Attaching package: 'xpose'
#> The following object is masked from 'package:stats':
#> 
#>     filter

dv_vs_pred(xpdb = xpdb_ex_pk,
           facets =c('SEX'),
           mapping = aes(point_color = SEX))
#> Using data from $prob no.1
#> Filtering data by EVID == 0
#> `geom_smooth()` using formula = 'y ~ x'
#> `geom_smooth()` using formula = 'y ~ x'
```

![](https://i.imgur.com/CLabXUQ.png)

<sup>Created on 2023-01-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sn248** [comment]
Thank you Samer, this solves my problem!

Satya
