### ISSUE TITLE
code ETA vs covariates plot

### ISSUE THREAD

**Issue by ftuhin2828** [UUPharmacometrics/xpose#214]
Hello,

Is there a code for plotting ETA vs covariates plot in xpose. I cannot seem to find it. It would be great help

Thanks,
Fazlur

**Comment by smouksassi** [comment]
you might find his useful:
https://certara.github.io/R-Xpose-NLME/reference/prm_vs_cov.html

**Comment by ftuhin2828** [comment]
thank you!

**Comment by guiastrennec** [comment]
@ftuhin2828 there is currently no such built in feature, but you can always make your own plot with the [general plotting functions](https://uupharmacometrics.github.io/xpose/reference/index.html#general-plotting-functions) of xpose such as `xplot_scatter`, `xplot_distrib`, ...
