### ISSUE TITLE
Change in error message

### ISSUE THREAD

**Issue by teunbrand** [UUPharmacometrics/xpose#217]
Hi there,

While preparing a new release of ggplot2, our reverse dependency check showed that one of the tests in your package has broken. In particular, we've updated an error message that seemed to be part of your test here:

https://github.com/UUPharmacometrics/xpose/blob/41052c95ec7755e70b7a8d2f5da1b12c3f79e2aa/tests/testthat/test-xpose_save.R#L26-L28

Our suggestion remain the same as those mentioned in #210 with the following changes: this time, you could test the solutions with `devtools::install_github('tidyverse/ggplot2@v3.4.2-rc')`, and the expected release will be in about two weeks. I'd like to re-iterate that testing exact error messages originating in upstream packages is fragile, and that snapshot tests might limit the impact of upstream message changes.

Best wishes,
Teun

**Comment by guiastrennec** [comment]
Thank you for your suggestion, fixed by @hadley in #220
