### ISSUE TITLE
error in read_nm_models when controlfile contains $PROB

### ISSUE THREAD

**Issue by AndreasCalvagone** [UUPharmacometrics/xpose#222]
Reading a controlstream only (i.e. no lst or ext available), throws an error when the Problem tag in the code is  abbreviated as "$PROB".

The issue is in various lines of code that search for a string that **starts** with $PROB  but is longer.
suggest to replace 
`stringr::str_detect(model, "^\\s*\\$PROB.+")`

with 

`stringr::str_detect(model, "^\\s*\\$PROB")`

**Comment by guiastrennec** [comment]
@AndreasCalvagone thanks for reporting this. I implemented your suggestion in the development version, could you please check that it works on your example and re-open the issue if not?
