### ISSUE TITLE
Reference for vpc_data() function

### ISSUE THREAD

**Issue by adcascone** [UUPharmacometrics/xpose#223]
Hello,

Would it be possible to provide a reference for the way in which the visual predictive check data are calculated via the vpc_data() function in xpose?

Thank you
Arianna

**Comment by bguiastr** [comment]
Hi @adcascone,
In xpose you can have the `vpc_data()` computed either by the [`vpc`](https://vpc.ronkeizer.com/) package or by [PsN](https://github.com/UUPharmacometrics/PsN/releases/download/v5.3.1/vpc_npc_userguide.pdf) if using the argument `psn_folder`. You can read more about this in the [xpose documentation on VPCs](https://uupharmacometrics.github.io/xpose/articles/vpc.html).
Best,
Ben
