### ISSUE TITLE
read_nm_tables() with argument combined=TRUE returns error and warning

### ISSUE THREAD

**Issue by adcascone** [UUPharmacometrics/xpose#225]
Hello,

I downloaded the example data that accompanies the `xpose` package from the GitHub at this link: [https://github.com/UUPharmacometrics/xpose/tree/master/inst/extdata](url)

I then tried to run the second set of example code in the read_nm_tables() documentation at this link: [https://uupharmacometrics.github.io/xpose/reference/read_nm_tables.html](url)

Specifically, the code I used was:
`nm_tables <- read_nm_tables(file = c('sdtab001','patab001'), combined=TRUE)`

However, this returned the following error and warning messages:
![image](https://github.com/UUPharmacometrics/xpose/assets/70408991/0c7b2337-43f8-4c9c-a29e-3321f7db7304)

Both files have the required `ID` column, as described in "Table format requirement" of the read_nm_tables() documentation page, but there are no notes about row number distinctions in the documentation. What is causing this error?

Thank you,
Arianna

**Comment by bguiastr** [comment]
Hi @adcascone,

This is the indented behavior if you have a look at the help for the `combined` argument in `read_nm_tables()`:

_Logical value indicating whether multiple tables should be combined into a single one. **If the number of rows does not match an error will be returned.**_


Which is the case in the example you are showing as `padtab001` was generated using the argument `FIRSTONLY`.

Of note, `read_nm_tables()`, `read_nm_model()`, `read_nm_files()` are functions used internally by xpose which were exported for advanced users. Thus, way I see `xpose` being used is as follows:
- If you need to import individual tabs, files into R use `read_nm_tables()` or `read_nm_files()`, respectively then process them using your standard data programing workflow (e.g. tidyverse)
- If you want to get an aggregated dataset use `xpose_data(...) %>% get_data()/get_files()/get_code()/get_summary()/get_prm()`. It is the easiest way to get what you want. `xpose_data()` was really designed to automatically give you access from R to all NONMEM output files nicely parsed without effort.  Use it in combination with `summary()`, `list_files()`, or `list_data()`

Hope this helps,

Ben
