### ISSUE TITLE
Multi-page graphs show all pages by default

### ISSUE THREAD

**Issue by MikeKSmith** [UUPharmacometrics/xpose#42]
I would suggest that perhaps multi-page graphs e.g. ind_plots show all pages by default rather than the last page. Setting page = 1:n is fine up to a point, but you need to go to the Help pages to find out how.

**Comment by guiastrennec** [comment]
Pro: it is more logical to have all pages plotted
Cons: it might get really slow with many pages or complex graphs due to ggplot2

Implemented in #43
