### ISSUE TITLE
`dplyr::n()` does not work when editing xpdb with dplyr verbs

### ISSUE THREAD

**Issue by guiastrennec** [UUPharmacometrics/xpose#54]
When editing an xpdb, `dplyr::n()` fails to return the proper number of rows of the actual dataset.
```r
xpdb_ex_pk %>%
mutate(N = n())
```

As temporary workaround one could use something like:
```r
xpdb_ex_pk %>%
mutate(N = length(ID))
```

Any suggestions on how to implement `dplyr::n()` in xpose are welcome

**Comment by smouksassi** [comment]
Dear Benjamin,
Great to see xpose in a modern format ! 
the xpdb_ex_pk is whole xp database I could not run the code above meaningfully.

**Comment by guiastrennec** [comment]
Dear Samer,

You are correct the `xpdb_ex_pk` is a full xpose database which comes with the package to exemplify the way the different functions work. In this new version of xpose we added methods for the most common dplyr verbs i.e. `filter()`, `slice()`, `distinct()`, `mutate()`, `select()`, `rename()`, `group_by()`, `ungroup()` and `summarize()`. Hence, you can use any of these function to modify an xpose database (i.e. data, files or special data like vpc) and easily get the plot that you want. You can learn more about these functions in the xpose help for [subsetting](https://uupharmacometrics.github.io/xpose/reference/subset_xpdb.html), [modiying](https://uupharmacometrics.github.io/xpose/reference/modify_xpdb.html) and [summarizing](https://uupharmacometrics.github.io/xpose/reference/summarize_xpdb.html) xpose database.

The example in the previous post should work. 

```r
library(xpose) 

# Create a new xpdb where the data contains a column N
xpdb_modified <- xpdb_ex_pk %>%
  mutate(N = length(ID))

# Extract the data for the estimation problem and check that the column N is present
xp_df <- get_data(xpdb_modified, problem = 1)
any(colnames(xp_df) == 'N')
```
If not, ensure that you have the latest version of xpose (v.0.3) which you can download [here](https://github.com/UUPharmacometrics/xpose/releases)

**Comment by sebastianueckert** [comment]
Hi Ben,

Back to your original issue. I just made a commit that hopefully fixes the problem. I think the cause was a scoping issue which led to the creation of the `n()` function in `xpdb$data`. So if the xpdb had 2 tables `n()` would always return 2. I just moved the call to the dplyr function outside of mutate and now it appears to work.

Seb

**Comment by guiastrennec** [comment]
Awesome thank you very much for finding the fix, I will check it out ASAP, you can go ahead with the PR. Do you mind updating the version to in the DESCRIPTION to 0.3.1? We also need to apply the same method to the `xpdb[['data']]$files` and `xpdb[['data']]$special` in `edit_xpose_data()`, but I can help you with that.

**Comment by sebastianueckert** [comment]
Don't worry, I can do these fixes.

**Comment by sebastianueckert** [comment]
Alright, implemented the same fix for files and special. I am just wondering if we need this functionality for special? In my opinion, special is a storage space for post-processing output, at the moment there is only vpc but there will be others in the future, so we would always need to adapt the code (which is cumbersome). At the same time, it is actually not obvious for a user to understand what is stored in special, so he would need to go into the data structure anyway.
Maybe we can discuss that F2F.

**Comment by guiastrennec** [comment]
Great thanks again for the help. We can talk about the edits to special F2F. We may have to reorganize the code to have dedicated function for each type of special dataset (i.e. VPC, bootstrap, scm, etc.) but I think it is needed e.g. for VPC if you want to change the panels labels or if you want to drop one of the strata you need this type of edits.
