### ISSUE TITLE
Warning messages despite quite=T

### ISSUE THREAD

**Issue by sebastianueckert** [UUPharmacometrics/xpose#57]
Hi Ben,

When loading output from a model that does not have tables, I get a warning even though I am using quite=T. Is this intended behavior?

Seb

**Comment by guiastrennec** [comment]
Hi Seb,

Yes, this is the intended behavior. `quiet = TRUE` acts on messages only. Warnings are more important and hence should not be easily silenced. If you want to suppress the warnings anyway you can use `options(warn=-1)` to suppress them globally (not recommended) or wrap the function you want to silence with `suppressWarnings()`. In rmarkdown you can also set the chunk option `warning=FALSE`. 

Now regarding your problem specifically you can tell `xpose_data()` not to look at tables with the `ignore = 'data'` argument.

Hope it helps,

Ben
