### ISSUE TITLE
Last page of individual plots

### ISSUE THREAD

**Issue by walsu** [UUPharmacometrics/xpose#74]
When I try to make individual plots, 'nrow' and 'ncol' are changed based on the remains of individuals.
For example, if I make an individual plot for 29 subjects with ncol=3 and nrow=3, last page of individual plot is ncol=2, nrow=1. I just want to make a plot for the last page as same with previous page  (ncol=3, nrow=3). Can I control this situation?

I used following script.

xpdb <- xpose_data(runno = '117', ext = '.out', prefix="", gg_theme = theme_bw2())
xpdb %>% ind_plots(ncol=3, nrow=3)

**Comment by guiastrennec** [comment]
This is the unfortunately the expected behavior of `ggforce::facet_wrap_paginate()` and `ggforce::facet_grid_paginate()`. You could post an issue on [ggforce](https://github.com/thomasp85/ggforce/issues)
