### ISSUE TITLE
Column names for NM files

### ISSUE THREAD

**Issue by sebastianueckert** [UUPharmacometrics/xpose#8]
I noticed that the NM files (.ext, .phi) have column names that correspond to the format you would get when reading a file with read.table (instead of readr). So for an .ext file the header in the xpdb is
`SIGMA.1.1.   OMEGA.1.1.  OMEGA.2.1.   OMEGA.2.2.  OMEGA.3.1.  OMEGA.3.2.`
rather than
``SIGMA(1,1)` `OMEGA(1,1)` `OMEGA(2,1)` `OMEGA(2,2)` `OMEGA(3,1)` `OMEGA(3,2)``
First, I thought this is a bug, but then I saw that an explicit replace is done in the code. So I wanted to ask why this was done and whether we shouldn't move to the second version?
In my opinion, the second version is clearer and more in line with modern R.

**Comment by guiastrennec** [comment]
Good catch Seb. 

This behavior is due to the implementation of a work around an issue with NSE which interprets OMEGA(..) or SIGMA() column names as functions and return error. Hence for consistency I will adopt the OMEGA.X.Y. notation for the files.

**Comment by sebastianueckert** [comment]
Thanks Ben. Is that still relevant with rlang?

**Comment by guiastrennec** [comment]
I am afraid so but I will try it out.

**Comment by sebastianueckert** [comment]
I can't let this go that quickly ;-) ...
What exactly do you mean by issues? I made a quick check and 

    xpdb %>% filter(`SIGMA(1,1)`>1, .source="ext")

works (after removing the regex replace). Also, the only errors I get when running the tests seem to be associated with a mismatch with the expected output.

**Comment by guiastrennec** [comment]
I think the issues were related to different dplyr version (<0.6 and >= 0.6) (but I need to check to be sure) and how do you send `SIGMA(1,1)` in a non interactive session?

**Comment by sebastianueckert** [comment]
You could do

    param<-'SIGMA(1,1)'
    xpdb %>% filter(!!param>1, .source="ext")

(this actually works if you have the latest version of dplyr)

**Comment by guiastrennec** [comment]
I ran some tests under different dplyr versions and indeed with `dplyr` versions ≤0.6 a column of the type `SIGMA(1,1)` is interpreted as a function in the `mutate_if()` and returns an error. More info about it can be found here: https://github.com/tidyverse/dplyr/issues/2243

I have changed the minimal `dplyr` version and removed the column conversion.
