### ISSUE TITLE
Avoid testing tibble output verbatim

### ISSUE THREAD

**Issue by krlmlr** [UUPharmacometrics/xpose#80]
xpose seems to be testing tibble output verbatim. The output has changed in the upcoming version 1.4.1. Could you please make sure that you only test output that is fully under your control?

https://github.com/tidyverse/tibble/blob/r-1.4.1/revdep/problems.md#xpose

**Comment by guiastrennec** [comment]
Thank you very much for the heads up @krlmlr, I will fix these tests ASAP.

**Comment by guiastrennec** [comment]
Fixed in #82
