### ISSUE TITLE
Summary Creation Fail

### ISSUE THREAD

**Issue by stephengreene** [UUPharmacometrics/xpose#84]
The majority of my runs create the following error:  Failed to create run summary. Evaluation error: invalid format '%02d'; use format %f, %e, %g or %a for numeric objects. 

Initially I thought it was because I was specifying the format of my output tables in the NM control stream. I removed these specifications and it seemed to rectify the issue until my next run when the same error occurred without specifying the format of the output table. FYI, I usually use the following format  in the NM control stream: FORMAT="t1PE14.7". I can still create basic GoF plots for my model but any information pulled from the run summary is incorrect (i.e. plot titles). Possible bug?

**Comment by guiastrennec** [comment]
Would it be possible for you to send me one of your .lst file that creates the error so that I can take a look at the problem?

**Comment by stephengreene** [comment]
Sure thing. Attached here are two .lst files. One has the format specifications and one does not.

Let me know if you need anything else. Thanks!

[RUN1_copy.txt](https://github.com/UUPharmacometrics/xpose/files/1598715/RUN1_copy.txt)

[RUN2_copy.txt](https://github.com/UUPharmacometrics/xpose/files/1598712/RUN2_copy.txt)

**Comment by stephengreene** [comment]
I think we found the issue. A colleague of mine discovered that if the $COV step failed and did not give an estimate of the time, the run summary would fail also. Might be worthwhile to update xpose to account for times when the $COV step fails to produce an estimation of time elapsed. Let me know your thoughts. Thanks!

**Comment by guiastrennec** [comment]
I had fixed the issue thanks to your lst files but did not get the chance to make the pull request. It was indeed a covariance step fail with time reported as `*******`. I have uploaded the fix (#85) on the dev branch you can test it out with:
`devtools::install_github('UUPharmacometrics/xpose@dev')`

You can reopen the issue if the problem persists

**Comment by stephengreene** [comment]
Tried it with the devtools package and the problem is persisting. For now I'll just remove the line.

**Comment by guiastrennec** [comment]
It is working for me with the file you sent. Make sure that you have xpose 0.4.1 installed. If the command above does not work you can also attempt to install it from my fork using the command:
`devtools::install_github('guiastrennec/xpose)`
