### ISSUE TITLE
"dir" argument ignored in read_nm_model if "file" is specified

### ISSUE THREAD

**Issue by MikeKSmith** [UUPharmacometrics/xpose#9]
When specifying both `dir` and `file` in read_nm_model (and in xpose_data), the `dir` argument seems to be ignored in line 52: `model <- readr::read_lines(file)`.

So when the user specifies:
`xpose_data(dir="./inst/extdata/", file="run001.lst")`
we get the error:
`Error: File run001.lst not found.`

**Comment by sebastianueckert** [comment]
The way the `dir` argument appears to be intended is for looking up models based on the runno, e.g.,
`xpose_data(1,dir="my_dir")`
would look for run1.lst in the directory my_dir.
The `file` argument, on the other hand, is expected to be a full path, i.e.,
`xpose_data(file='my_dir/run1.lst')`
Do you think this should behave differently?

**Comment by MikeKSmith** [comment]
It's confusing as it is just now... I would suggest:
runno + (dir==NULL) = local run NN.
runno + dir = lookup run NN in directory "dir"
file + (dir==NULL) = file is full path file name
file + dir = file is file.path(dir, file)

**Comment by guiastrennec** [comment]
I can see your point Mike but wouldn't this somehow make the runno, ext and prefix argument redundant with file? Note that the file argument was added for scripting by providing a full path directly to a function.

Please advise on whether we should:
1. Rename the file argument to string/path?
2. Implement the change suggested by Mike?

**Comment by sebastianueckert** [comment]
I don't think it makes 'file' redundant. If I understand well, then Mike's suggestion would only change the current behavior for file + dir, or? If so, then I think we could make this change, it is, in my opinion, quite logical.
(Renaming to path is fine by me too, but I don't love string)

**Comment by dpastoor** [comment]
I will +1 mike's logic to be similar to my expectation. file + dir = under the hood  file.path(dir, file). Also makes it easier to wrap 

```
read_xpose_data_dir_factory <- function(dir) {
   return(function(...) { 
       xpose_data(dir = dir, ...)
})
}

read_model <- read_xpose_data_dir_factory("../modeling")

read_model("run001.lst") # reads at ../modeling/run001.lst
```

**Comment by MikeKSmith** [comment]
Thanks for clarifying Devin, Sebastian - you're right that I was simply thinking that if the user supplies **both** file and dir then I'd assume that this would then create file.path(dir, file).

**Comment by guiastrennec** [comment]
Feature added in #24
