### ISSUE TITLE
labels not carried in multipanel plot

### ISSUE THREAD

**Issue by mct941** [UUPharmacometrics/xpose#91]
The labels are populated in the individual figure, but when the plots are combined together, only the templated text is presented.  Example code below:

xpdb <- xpose_data(dir=projpath,runno=runno)
p1 <- dv_vs_pred(xpdb)
p2 <- dv_vs_ipred(xpdb)
p3 <- res_vs_idv(xpdb)
p4 <- res_vs_pred(xpdb)

library(gridExtra)
grid.arrange(p1,p2,p3,p4, nrow=2)

**Comment by guiastrennec** [comment]
I am aware of this issue, template titles are not "yet" supported by gridExtra. You go around this issue if you use the ggplot2 function [annotation_custom](http://ggplot2.tidyverse.org/reference/annotation_custom.html). You can see an example of its use [here](https://stackoverflow.com/questions/35631889/ggplot2-align-multiple-plots-with-varying-spacings-and-add-arrows-between-them).

Hope it helps

**Comment by mct941** [comment]
ok thanks for the workaround.

**Comment by kestrel99** [comment]
`annotation_custom` is quite cumbersome to use. Do you think it would be possible to add a keyword-aware multiplot wrapper to xpose?

**Comment by guiastrennec** [comment]
I can't promise anything but I will check if it is possible when I get some time to work on xpose.
