### ISSUE TITLE
Access by `::` seems to not work the same as direct access

### ISSUE THREAD

**Issue by mattfidler** [UUPharmacometrics/xpose#95]
Hi @guiastrennec 

Again, thanks for the package.  I wanted to point out some strange inconsistency when looking at `nlmixr`'s use of `xpose`

It is probably reproducable with other examples, but I will use nlmixr
```R
library(nlmixr)
library(xpose.nlmixr)
one.compartment.saem <- function() {
    ini({
        tka <- .5   # Log Ka
        tcl <- -3.2 # Log Cl
        tv <- -1    # Log V
        eta.ka ~ 1
        eta.cl ~ 2
        eta.v ~ 1
        add.err <- 0.1
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        d/dt(depot) = -ka * depot
        d/dt(center) = ka * depot - cl / v * center
        cp = center / v
        cp ~ add(add.err)
    })
}
fit <- nlmixr(one.compartment.saem, theo_sd, est="saem")
```

Then `xpose.nlmixr` creates the `xpose` object:

```R
xpdb <- xpose_data_nlmixr(fit)
```

With `::` access I get:

```R
>   xpose::dv_vs_ipred(xpdb)
Using data from $prob no.1
Filtering data by EVID == 0
Error: Columns `problem`, `subp`, `label` must be length 1 or 6, not 4, 4, 4
```

However, with direct access everything is OK:
```R
>   xpose::dv_vs_ipred(xpdb)
```

**Comment by rfaelens** [comment]
+1
This issue occurs because x$xpose$fun in parse_title has 3 elements: the package name, the `::` operator and the `dv_vs_ipred` function.

**Comment by rfaelens** [comment]
This occurs because `dv_vs_idv` calls `xplot_scatter` with plotname `as.character(match.call()[[1]])`.
When you call a function with the package name, `as.character.call` will return a vector of size 3.

**Comment by rfaelens** [comment]
The solution is probably to collapse this. That is the easiest fix.
I made this change in my fork and want to open a pull request. However, it seems the contribution guidelines are out of date... Should I open a PR to the `dev` branch (last commit 8months ago) or to the `master` branch?
@guiastrennec ?

**Comment by guiastrennec** [comment]
@rfaelens sorry for the delay in my response. You can a PR to the master branch directly.
